### ISSUE TITLE
nice work

### ISSUE THREAD

**Issue by jespersgaard** [linhntaim/katniss#1]
hello

really nie work. are you planning on updating to laravel 5.3?

**Comment by linhntaim** [comment]
@jespersgaard Hi. Thank you. I'm busy with my job, have no free time, so I did not update this repo for weeks.

But yeap, I'm still on the way updating it to the latest version of Laravel. Laravel 5.3 came with lots of changes, it requires me to reconstruct the code. I'm also building public/private API interfaces for the internal system to easily exchange data with external ones or itself. They take time to design & implement.

Thanks again. Your comment encourage me a lot. I'll continue to work on it and may release a Laravel-5.3-based version next week.

**Comment by linhntaim** [comment]
Update to version 2.0 (with base framework Laravel 5.3)
See update information: [Katniss 2.0](https://github.com/linhntaim/katniss/releases/tag/v2.0.0)
See readme: [ReadMe](https://github.com/linhntaim/katniss/blob/master/readme.md)
